
services:
  db:
    image: mysql:latest
    container_name: mysql-compose-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: AdminSommar!123
    ports:
      - "3306:3306"
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      -  db_data:/var/lib/mysql
    networks:
      - internalNetwork

  nodeapp:
    container_name: nodeapp-compose-container
    build: ./server
    image: nodeapp
    volumes:
      - ./server:/usr/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=AdminSommar!123
      - DB_NAME=mydatabase
      - DB_CONNECTION_LIMIT=20
      - SERVER_PORT=3000
      - ACCESS_TOKEN_SECRET=146ccd02d4fe4848f8f36aa05170a1817995b27b306f7096475d18c8bba8ce12
    depends_on:
      - db
    networks:
      - internalNetwork


  vueapp:
    container_name: vueapp-compose-container
    build: ./vue-project
    image: vueapp
    volumes:
      - ./client:/usr/code
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - SERVER_PORT=3000
    depends_on:
      - nodeapp
    networks:
      - internalNetwork

networks:
  internalNetwork:
    driver: bridge

  

volumes:
  db_data: