version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql-compose-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: AdminSommar!123
    ports:
      - "3306:3306"
    volumes:
     -  db_data:/var/lib/mysql

volumes:
  db_data: